Added multiply and division tokens

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -7,27 +7,23 @@ go fmt ./...
 # vet all files
 go vet ./...
 if [[ $? != 0 ]]; then
-  exit 1
+  PASS=false
 fi
 
 # run all tests
 go test ./...
 if [[ $? == 1 ]]; then
-  exit 1
+  PASS=false
 fi
 
-STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")
-for FILE in $STAGED_GO_FILES
-do
-  # lint any changed files
-  golint "-set_exit_status" $FILE
-  if [[ $? == 1 ]]; then
-    PASS=false
-  fi
-done
+# lint all files
+golint "-set_exit_status" ./...
+if [[ $? == 1 ]]; then
+  PASS=false
+fi
 
 if ! $PASS; then
-  printf "Commit Failed\n"
+  printf "Commit failed by pre-commit checks!\n"
   exit 1
 fi
 
